### ISSUE TITLE
Drag and drop not working on MacOS

### ISSUE THREAD

**Issue by createrme** [ZYinMD/myfaveTT#1]
Drag and drop of an empty folder on MacOS results in the opening of a new window.

**Comment by ZYinMD** [comment]
What's your macOS version and chrome version? Have you tested mac only, or tested both win and mac and know they behave differently?

**Comment by createrme** [comment]
Tested with "macOS Big Sur - Chrome (Version 96.0.4664.55)", tested with macOS only.

**Comment by ZYinMD** [comment]
Does the square box turn green before you drop the folder?

**Comment by createrme** [comment]
No it does not.

**Comment by ZYinMD** [comment]
If you drag any random link over the box, or select a random piece of text and drag it over the box, does the box turn green?

**Comment by createrme** [comment]
No, that does not happen either.

![image](https://user-images.githubusercontent.com/94972040/143259924-a06848ce-4fd6-44b4-9e89-22d21ba41eba.png)

**Comment by createrme** [comment]
Can you as a fallback perhaps make the + clickable, so you can manually select the empty folder.

**Comment by ZYinMD** [comment]
Yes I can, but I also want to find out what's wrong. I'll need to get a mac. 

Meanwhile, could you help me test one more thing: don't drag the sentence as shown in you screenshot, or anything from within the dark sidebar, instead, drag something over from the tiktok site on the right, and see if the box turns green?

If it does turn green, what happens if you release the mouse?

Thanks.

**Comment by createrme** [comment]
The result is the same. I am not able to drag something in the sidebar and turn it green (link, text, image,..). Releasing the mouse also will just result in nothing.

![image](https://user-images.githubusercontent.com/94972040/143270329-726dc967-4817-4039-a290-e5979dba04bf.png)

**Comment by ZYinMD** [comment]
Thanks, I'll see what I can do.

**Comment by ZYinMD** [comment]
A new patch should've been out. A new clickable "browse" button was added. If you don't see it, try restart chrome to trigger the auto update, or wait a day or two.

**Comment by createrme** [comment]
The browse link appears and after selecting the folder manually it downloads as expected. Thanks for the fix!

**Comment by ZYinMD** [comment]
Hi, could you do me a favor and help me test a drag-and-drop behavior on mac? I don't have a mac on hand at this moment.

It's super easy, should take less than 1 minute:

Visit https://zyinmd.github.io/drop-demo/, and see the last 2 lines: "firefox on mac" and "safari on mac" are "untested". Could you help me test those 2? The behavior might be either "works" or "works on half of the box".

Thanks very much!!
